// @ts-ignore Generated by OpenNext during the custom build.
import openNextHandler from "./frontend/.open-next/worker.js";

interface Env {
  PUBLIC_APP_URL?: string;
}

export default {
  fetch: openNextHandler.fetch,

  async scheduled(
    controller: ScheduledController,
    env: Env,
    ctx: ExecutionContext,
  ) {
    const origin =
      env.PUBLIC_APP_URL || "https://sports-betting.abl-slancry.workers.dev";

    const refresh = async () => {
      const upcomingResponse = await fetch(
        `${origin}/api/v1/events/upcoming?hours=168`,
      );
      if (!upcomingResponse.ok) {
        throw new Error(`Upcoming refresh failed: ${upcomingResponse.status}`);
      }

      await fetch(`${origin}/api/v1/events/value-bets`);

      if (controller.cron === "15 */6 * * *") {
        const upcoming = (await upcomingResponse.json()) as Array<{ id: number }>;
        await Promise.allSettled(
          upcoming.slice(0, 2).flatMap((event) => [
            fetch(`${origin}/api/v1/events/${event.id}/players`),
            fetch(`${origin}/api/v1/ai/context/${event.id}`),
          ]),
        );
      }
    };

    ctx.waitUntil(refresh());
  },
} satisfies ExportedHandler<Env>;
