// @ts-ignore Generated by OpenNext during the custom build.
import openNextHandler from "./frontend/.open-next/worker.js";

interface Env {
  PUBLIC_APP_URL?: string;
}

export default {
  fetch: openNextHandler.fetch,

  async scheduled(
    controller: ScheduledController,
    env: Env,
    ctx: ExecutionContext,
  ) {
    const origin =
      env.PUBLIC_APP_URL || "https://sports-betting.abl-slancry.workers.dev";

    const refresh = async () => {
      const mode = controller.cron === "15 */6 * * *" ? "full" : "fast";
      const response = await fetch(
        `${origin}/api/v1/admin/data-refresh?mode=${mode}&trigger=cron&hours=168`,
        {
          method: "POST",
        },
      );
      if (!response.ok) {
        throw new Error(`Data refresh failed: ${response.status}`);
      }

      for (const profileId of [
        "prudent_3",
        "value_5",
        "aggressive_10",
      ]) {
        const profileResponse = await fetch(
          `${origin}/api/v1/daily-picks/profiles/${profileId}/refresh`,
          { method: "POST" },
        );
        if (!profileResponse.ok) {
          console.warn(
            `Daily profile ${profileId} refresh failed: ${profileResponse.status}`,
          );
        }
      }

      const picksResponse = await fetch(
        `${origin}/api/v1/daily-picks/refresh?trigger=cron`,
        {
          method: "POST",
        },
      );
      if (!picksResponse.ok) {
        console.warn(`Daily picks refresh failed: ${picksResponse.status}`);
      }

      const alertsResponse = await fetch(`${origin}/api/v1/alerts/scan`, {
        method: "POST",
      });
      if (!alertsResponse.ok) {
        console.warn(`Automated alerts scan failed: ${alertsResponse.status}`);
      }
    };

    ctx.waitUntil(refresh());
  },
} satisfies ExportedHandler<Env>;
