// @ts-ignore Generated by OpenNext during the custom build.
import openNextHandler from "./frontend/.open-next/worker.js";

interface Env {
  PUBLIC_APP_URL?: string;
}

export default {
  fetch: openNextHandler.fetch,

  async scheduled(
    controller: ScheduledController,
    env: Env,
    ctx: ExecutionContext,
  ) {
    const origin =
      env.PUBLIC_APP_URL || "https://sports-betting.abl-slancry.workers.dev";

    const refresh = async () => {
      const mode = controller.cron === "15 */6 * * *" ? "full" : "fast";
      const response = await fetch(
        `${origin}/api/v1/admin/data-refresh?mode=${mode}&trigger=cron&hours=168`,
        {
          method: "POST",
        },
      );
      if (!response.ok) {
        throw new Error(`Data refresh failed: ${response.status}`);
      }
    };

    ctx.waitUntil(refresh());
  },
} satisfies ExportedHandler<Env>;
